/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Reydel
 */
public class FOR_UPDATE extends javax.swing.JFrame {

    /**
     * Creates new form FOR_UPDATE
     */
    private ORDERS mainFrame;

    private int rowIndex;
    private String product_name;
    private String product_size;
    private String product_price;
    private String product_quantity;
    private String product_total;

    public FOR_UPDATE() {
        initComponents();

    }

    public void setMainFrame(ORDERS mainFrame) {
        this.mainFrame = mainFrame;
    }

    public void setDetails(int rowIndex, String product_name, String product_size, String product_price, String product_quantity, String product_total) {

        this.rowIndex = rowIndex;
        this.product_name = product_name;
        this.product_size = product_size;
        this.product_price = product_price;
        this.product_quantity = product_quantity;
        this.product_total = product_total;

        UPDATE_PRODUCT_NAME.setText(product_name);
        UPDATE_PRODUCT_SIZE.setText(product_size);
        UPDATE_PRODUCT_PRICE.setText(product_price);
        UPDATE_PRODUCT_QTY.setText(product_quantity);
        UPDATE_PRODUCT_TOTAL.setText(product_total);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UPDATE_PRODUCT_TOTAL = new javax.swing.JLabel();
        UPDATE_PRODUCT_NAME = new javax.swing.JLabel();
        UPDATE_PRODUCT_SIZE = new javax.swing.JLabel();
        UPDATE_PRODUCT_QTY = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        UPDATE_PRODUCT_PRICE = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        FOR_UPDATE_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UPDATE_PRODUCT_TOTAL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UPDATE_PRODUCT_TOTAL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE_PRODUCT_TOTAL.setText("DASDA");
        jPanel1.add(UPDATE_PRODUCT_TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 230, 50));

        UPDATE_PRODUCT_NAME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UPDATE_PRODUCT_NAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE_PRODUCT_NAME.setText("DA");
        jPanel1.add(UPDATE_PRODUCT_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 230, 50));

        UPDATE_PRODUCT_SIZE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UPDATE_PRODUCT_SIZE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE_PRODUCT_SIZE.setText("DASDA");
        jPanel1.add(UPDATE_PRODUCT_SIZE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 50));

        UPDATE_PRODUCT_QTY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UPDATE_PRODUCT_QTY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE_PRODUCT_QTY.setText("DASDA");
        jPanel1.add(UPDATE_PRODUCT_QTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 230, 50));

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 50, 40));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 50, 40));

        UPDATE_PRODUCT_PRICE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UPDATE_PRODUCT_PRICE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE_PRODUCT_PRICE.setText("DASDA");
        jPanel1.add(UPDATE_PRODUCT_PRICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 230, 50));

        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 100, 40));

        FOR_UPDATE_BUTTON.setText("UPDATE");
        FOR_UPDATE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOR_UPDATE_BUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(FOR_UPDATE_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 423, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double price = Double.parseDouble(UPDATE_PRODUCT_PRICE.getText());
        int quantity = Integer.parseInt(UPDATE_PRODUCT_QTY.getText());

        int quant = quantity + 1;
        UPDATE_PRODUCT_QTY.setText(String.valueOf(quant));

        double total = quant * price;
        UPDATE_PRODUCT_TOTAL.setText(String.valueOf(total));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double price = Double.parseDouble(UPDATE_PRODUCT_PRICE.getText());
        int quantity = Integer.parseInt(UPDATE_PRODUCT_QTY.getText());

        int quant = quantity - 1;
        UPDATE_PRODUCT_QTY.setText(String.valueOf(quant));

        double total = quant * price;
        UPDATE_PRODUCT_TOTAL.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FOR_UPDATE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOR_UPDATE_BUTTONActionPerformed

        String productName = UPDATE_PRODUCT_NAME.getText();
        String size = UPDATE_PRODUCT_SIZE.getText();
        double price = Double.parseDouble(UPDATE_PRODUCT_PRICE.getText());
        int quantity = Integer.parseInt(UPDATE_PRODUCT_QTY.getText());
        double total = Double.parseDouble(UPDATE_PRODUCT_TOTAL.getText());

        mainFrame.updateMainTable(rowIndex, productName, size, price, quantity, total);

        dispose();
    }//GEN-LAST:event_FOR_UPDATE_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FOR_UPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FOR_UPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FOR_UPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FOR_UPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FOR_UPDATE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FOR_UPDATE_BUTTON;
    private javax.swing.JLabel UPDATE_PRODUCT_NAME;
    private javax.swing.JLabel UPDATE_PRODUCT_PRICE;
    private javax.swing.JLabel UPDATE_PRODUCT_QTY;
    private javax.swing.JLabel UPDATE_PRODUCT_SIZE;
    private javax.swing.JLabel UPDATE_PRODUCT_TOTAL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
