
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jhonl
 */
public class Savepurchase extends javax.swing.JFrame {

    Connection conn;

    Connection con;
    PreparedStatement deletePst = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;

    /**
     * Creates new form PAYMENT
     */
    public Savepurchase() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        total_income = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable2 = new javax.swing.JTable();
        total = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtable.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sales_id", "product name", "size", "price", "qty"
            }
        ));
        jScrollPane1.setViewportView(jtable);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1060, 240));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setText("Total Income:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 100, 30));

        total_income.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        total_income.setText("00");
        jPanel7.add(total_income, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 110, 30));

        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 130, 40));

        jtable2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "total ", "payment", "balance"
            }
        ));
        jScrollPane2.setViewportView(jtable2);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 630, 240));

        total.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        total.setText("result");
        total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel7.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 130, 40));

        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        jButton3.setText(">>");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 490, 90, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton2ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        int sum = 0;

        for (int a = 0; a < jtable2.getRowCount(); a++) {
            double totalprice = Double.parseDouble(jtable2.getValueAt(a, 1).toString());
            sum += totalprice;
        }

        total_income.setText(Integer.toString(sum));
    }//GEN-LAST:event_totalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ORDERS s = new ORDERS();
        s.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = (Connection) DBCONNECTION.getConnection();
        DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
        model.setRowCount(0);

        try {

            // Select data from the sales table
            String selectQuery = "SELECT * FROM sales";

            PreparedStatement selectPst = conn.prepareStatement(selectQuery);
            ResultSet selectRs = selectPst.executeQuery();

            // Populate the JTable with retrieved data
            while (selectRs.next()) {
                int salesId = selectRs.getInt("id");
                double subtotal = selectRs.getDouble("subtotal");
                double balance = selectRs.getDouble("payment");
                double payment = selectRs.getDouble("balance");

                model.addRow(new Object[]{salesId, subtotal, balance, payment});
            }

            JOptionPane.showMessageDialog(this, "Data retrieved and populated into the JTable successfully.");
        } catch (SQLException ex) {
            Logger.getLogger(ORDERS.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel table = (DefaultTableModel) jtable.getModel();
        table.setRowCount(0);

        try {

            // Select data from the purchase table
            String selectQuery = "SELECT * FROM purchase";

            PreparedStatement selectPst = conn.prepareStatement(selectQuery);
            ResultSet selectRs = selectPst.executeQuery();

            // Populate the JTable with retrieved data
            while (selectRs.next()) {

                int salesId = selectRs.getInt("sales_id");
                String productName = selectRs.getString("product_name");
                String size = selectRs.getString("size");
                double price = selectRs.getDouble("price");
                int quantity = selectRs.getInt("qty");

                table.addRow(new Object[]{salesId, productName, size, price, quantity});
            }

            JOptionPane.showMessageDialog(this, "Data retrieved and populated into the JTable successfully.");
        } catch (SQLException ex) {
            Logger.getLogger(ORDERS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Savepurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Savepurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Savepurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Savepurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Savepurchase().setVisible(true);
            }
        });
    }

// 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtable;
    private javax.swing.JTable jtable2;
    private javax.swing.JButton total;
    private javax.swing.JLabel total_income;
    // End of variables declaration//GEN-END:variables
}
